### ISSUE TITLE
Color filter is not applied properly

### ISSUE THREAD

**Issue by aloklearning** [erikagtierrez/multiple-media-picker#11]
I appreciate the changes you made in your library, but unfortunately after testing in my app I have to give the inference that your given color changing property is working only for this `<color name="titleSelectedTabColor">#000000</color>` else the two of the three codes is not working which are : 
`<color name="titleTextColor">#000000</color>` and 
`<color name="titleTabColor">#000000</color>` 

however `<color name="titleTextColor">#000000</color>`,  this code changes the color of backButton which is present at the title bar also known as homeAsUpEnabled arrow.

and to be precise the `<color name="titleTabColor">#000000</color>`,  this particular code, I don't have any about what it is for actually. Thanks for updating the code again. Will be waiting to hear from you soon.

Attaching the result's link for the better understanding : [Resulting Image](https://drive.google.com/open?id=1lYSskQ-XhrarAPIL2wDCZldoOeCgbtL7) 
**I have used all the three color coding in my color.xml the above is the result I found**. Thanks

**Comment by erikagtierrez** [comment]
Hello! Happy to see you tested already! 😃 
Ok, so first the  `"titleTabColor"` references to the unselected tab. I'm looking at your pic and you're only using image selection and as there is no "other" unselected tab, you're not seeing it.

I decided to use the `"titleTextColor"` exactly because it changes the back button color, maybe it should be separated? 😕  

Make sure you're adding the reference to the `"titleTextColor"` in your styles.xml inside your theme and let me know if it resolves the issue for you! 
```xml 
<item name="titleTextColor">@color/titleTextColor</item>
``` 
![Result](https://lh6.googleusercontent.com/CZO2nZNqmnwGCX62Z5XEyK_CHCJc9zdzJ3Tu4R42IW5VMBbzVI92M3IlFZL3WEvXKBrimHbqluf4J5CGi-5c=w1600-h826-rw)

**Comment by aloklearning** [comment]
Sweet! It has done the magic. I must suggest you to please update this in the documentation also, since this wonderful library must be used correctly. Since I have used the mode = 3, so you were not able to look to the other side of the unselected tab. What I would suggest that if you can make the UI look good as when we see in the mode = 1, taking full space in the page with the two tabs. But when the mode = 3 selected or if there is just one tab the tab comes to the middle and make the UI look a little bit weirder.

**Comment by erikagtierrez** [comment]
Done with the documentation update 🎉 . I'm closing this issue and I'll definetely keep your suggestion in mind!
