### ISSUE TITLE
Filter content

### ISSUE THREAD

**Issue by jeffersonlicet** [erikagtierrez/multiple-media-picker#2]
Is there any method to filter media and toggle multiple selection? Thank you.

**Comment by erikagtierrez** [comment]
Hey @jeffersonlicet !
Toggle multiple selection support can be added to the next version! About the other question.. what do you exactly mean with filter media?

**Comment by jeffersonlicet** [comment]
Thank you for your time. 
What i mean with "Media filter": it to filter the media type: photos, videos...

**Comment by erikagtierrez** [comment]
@jeffersonlicet Ok! Tomorrow I'll try to upload a new version of the library with: 
- Limit number of pictures to select
- Toggle multiple selection
 And I'll consider the disable for the media types because it already separates the media(photos and videos) but It could be nice to disable any of them in case you need pictures or videos only!
As soon as I upload the new version I'll close the issue

**Comment by jeffersonlicet** [comment]
Awesome! Thank you.

**Comment by erikagtierrez** [comment]
Really sorry about the late answer 😿 😓 
Today I uploaded the version **1.0.3** where you can define if there's image and video selection or just one of them. Optional max selection is added too, so you could just set 1 to toggle multiple selection
